version: '2'
services:
  web:
    image: socnetgen:latest
    ports:
      - 8069:8069
    depends_on:
      - db
  db:
    container_name: covidisimteam_db
    image: postgres:12.2
    volumes:
      - covidisimteam_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  covidisimteam_db: {}